### ISSUE TITLE
Can't create or restore any wallet

### ISSUE THREAD

**Issue by Dalto1** [monerujo-io/aeonwallet#6]
My client wallet is always crashing when I try to create or restore by the seed a wallet.
![crash](https://user-images.githubusercontent.com/21979600/41205234-732b6af6-6cbd-11e8-9b52-ab8df89d032f.png)

**Comment by Dalto1** [comment]
I'm on LineageOS 14.1 on my phone (KIW-L24)

**Comment by m2049r** [comment]
can you open existing wallets?

**Comment by m2049r** [comment]
also, please try https://github.com/monerujo-io/aeonwallet/releases/download/v0.2.0/monerujoAE-0x2x0_armeabi-v7a.apk

**Comment by m2049r** [comment]
also it would be very helpful if you could do this and mail me the log output: https://support.apteligent.com/articles/knowledge_base/How-to-Collect-Logs-via-Command-Line-ADB-on-Android-Devices

**Comment by Dalto1** [comment]
This isn't working
> also, please try https://github.com/monerujo-io/aeonwallet/releases/download/v0.2.0/monerujoAE-0x2x0_armeabi-v7a.apk


I'll try to investigate with ADB

**Comment by Dalto1** [comment]
I can't open the monero wallet or create another one, so it's seems to be related to lineageos since i was able to create a wallet and open it before the weekly update.

Update : even if i update my lineage os, im not able to access anything.

**Comment by Dalto1** [comment]
@m2049r I mailed you the log

**Comment by Dalto1** [comment]
Do you got any news for this?

**Comment by m2049r** [comment]
sorry - must have missed you. lineageos 15.1 (i think) seems to have issues with android encryption features on certain hardware. basically - it cannot be fixed - except by lineageos.

**Comment by Dalto1** [comment]
On the last mail conversation we had, you said 

> In one of the next releases I will be allowing the use of normal (i.e. not crazy) passwords, and so the encryption will not go in effect and so you will not be getting the crashes (but will need to use very good passwords!). Maybe 2-3 months.

Is this a possible solution?
